config/routes.rb
Rails.application.routes.draw do

mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'
namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings,:time_zones
  resources :profiles, :manage_mobile_apps, :downloads, :external_login
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :eventfeatures_contents
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events do
    end
  end
  resources :mobile_applications do
    resources :external_login
  end
  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :warehouse_timers
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s,:telecallers,:invitee_datas,:my_travels,:venue_sections,:invitee_accesses,:invitee_searches
    
    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations

  end
  # resources :imports
end
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout 'admin'

  load_and_authorize_resource :except => [:create]
  before_filter :authenticate_user
  before_filter :authorize_client_role, :find_client_association
  before_filter :check_moderator_role, :feature_redirect_on_condition, :only => [:index]
  before_filter :get_event_names, :only => [:new, :create, :edit, :update]

  def index
    if params["type"].present?
      @events = Event.sort_by_type(params["type"], @events)
    end
    if (params[:search].present? && params[:search][:order_by].present? && params[:search][:order_by] == "All") || (params[:search].present? && params[:search][:order_by_status].present? && params[:search][:order_by_status] == "All")
      @events
    else 
      @events = Event.search(params, @events) if params[:search].present?
    end
    @select = true if (params[:feature].present? and params[:redirect_page].present? and params[:redirect_page] == "copy_event")
    @events = @events.ordered.paginate(page: params[:page], per_page: 10) if (@select != true)
    mobile_application_ids = @events.pluck(:mobile_application_id)
    single_mobile_application_ids = @client.mobile_applications.where('id IN (?) and application_type = ?', mobile_application_ids, 'single event').pluck(:id)
    if single_mobile_application_ids.present?
      @multi_mobile_applications = @client.mobile_applications.where('id NOT IN (?)', single_mobile_application_ids)
    else
      @multi_mobile_applications = @client.mobile_applications
    end
  end

  def new
    @event = @client.events.build
    @event.images.build unless (params[:marketing_app].present? and params[:marketing_app] == "true")
  #@event.event_venues.build    
  @themes = Theme.find_themes()
    @default_features = @event.set_features_default_list
    @present_feature = @event.set_features rescue []
    if (params[:marketing_app].present? and params[:marketing_app] == "true")
      result = @event.create_marketing_app_event
      if result == "true"
        redirect_to new_admin_event_mobile_application_path(:event_id=>@event.id,:old_one => true)
      else
        redirect_to :back
      end
    end
  end
  
  def create
    @event = @client.events.new(events_params)
    @event.set_time(params["event"]["start_event_date"], params["event"]["start_time_hour"], params["event"]["start_time_minute"], params["event"]["start_time_am"], params["event"]["end_event_date"], params["event"]["end_time_hour"], params["event"]["end_time_minute"], params["event"]["end_time_am"]) rescue nil
    @event.set_status_for_licensee if current_user.has_role? :licensee_admin
    @themes = Theme.find_themes()
    if @event.save 
      if params[:event][:copy_event].present? and params[:event][:copy_event] == 'yes'
        event = Event.find(params[:event][:parent_event_id])
        @event.update_columns(parent_id: event.id,default_feature_icon: event.default_feature_icon,about: event.about)
        if params[:event][:copy_content].present?
          @event.copy_event_associations_from(event)
        elsif params[:event][:custom_content].present?
          @event.copy_custom_event_associations_from(event, params)
        end
      end

      @event.add_default_invitee if @event.mobile_application.present?
      redirect_to admin_client_event_path(:client_id => @event.client_id, :id => @event.id)
    else
      #@landing_page = @event.landing_page if @event.landing_page.present?
      @default_features = @event.set_features_default_list
      @present_feature = @event.set_features rescue []
      render :action => 'new'
    end
  end
    
  def show
    redirect_to admin_client_event_path(:client_id => @client.id, :id => @event.id, :analytics => "true") if params[:detailed_analytics].nil? and params[:analytics].nil? and @event.mobile_application.present? #and (!current_user.has_role_for_event?("db_manager", @event.id,session[:current_user_role]))
    mobile_application_ids = @events.pluck(:mobile_application_id).compact
    single_mobile_application_ids = @client.mobile_applications.where('id IN (?) and application_type = ?', mobile_application_ids, 'single event').pluck(:id)
    @multi_mobile_applications = single_mobile_application_ids.present? ? @client.mobile_applications.where('id NOT IN (?)', single_mobile_application_ids) : @client.mobile_applications
    if params[:detailed_analytics].present? and @event.mobile_application.present?
      params[:filter_date], params[:start_date] = 'date range', params[:start_date].present? ? params[:start_date].to_date : Date.today - 2.weeks
      params[:end_date] = params[:end_date].present? ? params[:end_date].to_date : Date.today
      @detailed_analytics_counts = Analytic.get_detailed_analytics(params)
    elsif params[:analytics].present? and @event.mobile_application.present? and (params[:end_date].present? and params[:start_date].present?) and (params[:end_date].to_date - params[:start_date].to_date).to_i > 31
      @date_filter_error = true
    elsif params[:analytics].present?  
      @live_analytics = Analytic.get_live_analytics(params)
    end
  end

  def edit
    @present_users = @event.users.pluck(:id)
    @users = User.all
    @themes = Theme.find_themes()
    @default_features = @event.set_features_default_list
    @present_feature = @event.set_features
    #@event.event_venues.build
  end

  def update
    if params[:status].present?
      update_status_and_redirect and return
    elsif params[:schedule_type].present?
      schedule_date = params[:schedule_type] == "ongoing" ? Date.today : Date.today + 1
      @event.update(:start_event_date => schedule_date) rescue nil
      redirect_to admin_client_events_path(:client_id => @client.id, :page => params[:page]) rescue nil
    else
      if params["event"]["start_event_date"].present?
        @event.set_time(params["event"]["start_event_date"], params["event"]["start_time_hour"], params["event"]["start_time_minute"], params["event"]["start_time_am"], params["event"]["end_event_date"], params["event"]["end_time_hour"], params["event"]["end_time_minute"], params["event"]["end_time_am"]) rescue nil
      end
      if @event.update_attributes(events_params)
        if params[:event][:copy_event].present? and params[:event][:copy_event] == 'yes'
          event = Event.find(params[:event][:parent_event_id])
          @event.update_columns(parent_id: event.id,default_feature_icon: event.default_feature_icon)   
          if params[:event][:copy_content].present?
            @event.copy_event_associations_from(event)
          elsif params[:event][:custom_content].present?
            @event.copy_custom_event_associations_from(event, params)
          end
          redirect_to admin_event_mobile_application_path(:id => @event.mobile_application.id, :event_id => @event.id, :type => "show_engagement")
        elsif params[:set_activity_feed_bool].present?
          redirect_to admin_event_mobile_application_path(:id => @event.mobile_application.id, :event_id => @event.id, :type => "show_engagement")
        else
          redirect_to admin_client_events_path(:client_id => @client.id)
        end
      else
        @default_features = @event.set_features_default_list
        @present_feature = @event.set_features
        @themes = Theme.find_themes()
        render :action => "edit"
      end
    end
  end

  def destroy
    if @event.destroy
      redirect_to admin_client_events_path(:client_id => @event.client_id)
    end
  end

  protected

  def get_event_names
    @event_names = @client.events.where(marketing_app: nil).where.not(status: 'rejected').pluck(:event_name, :id)
    source_event = Event.find(params[:event_id])
    @active_modules = source_event.get_active_module
  end

  def feature_redirect_on_condition
    if params[:feature].present? and params[:feature]  != "events"
      event_count = (current_user.has_role? "moderator" or current_user.has_role? :event_admin or current_user.has_role? "telecaller" or current_user.has_role? :db_manager) ? @events.count("events.id") : @events.count
      if params[:event_id].present? or (@events.present? and event_count == 1 and params[:feature] != "mobile_application" and params[:feature] != "mobile_applications")
        @event = (event_count == 1) ? @events.first : @events.find(params[:event_id])
        if params[:feature] == "mobile_application"
          if @event.present? and params[:type] == 'remove'
            @event.update_column(:mobile_application_id, nil)
            redirect_to :back
          elsif @event.present? and params[:redirect_page] == "show"
            redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application_id)
          elsif @event.present? and params[:redirect_page] == "edit"
            redirect_to edit_admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application_id)
          else
            @event.update_column(:mobile_application_id, params[:mobile_application_id])
            @event.add_default_invitee
            redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application_id)
          end
        elsif params[:feature] == "mobile_applications" and params[:client_id].present?
          if @event.mobile_application.present?
            redirect_to edit_admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application_id)
          else
            redirect_to new_admin_event_mobile_application_path(:event_id => @event.id)
          end
        elsif params[:feature] == "mobile_applications"
          if @event.mobile_application.present?
            redirect_to admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application.id)
          else
            redirect_to admin_client_mobile_applications_path(:client_id => @event.client_id)
          end  
        elsif params[:feature] == "analytics"
          if @event.mobile_application.present?

app/views/admin/events/_advance_search.html.haml
= form_tag admin_client_events_url(:client_id => @client.id), :method => :get do
  .mdl-grid
    = custom_text_field_tag "search[name]", "Search by Name", adv_search_value(params,"name")
    = #custom_text_field_tag "search[code]", "Search by Code", adv_search_value(params,"code")

    .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
      .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
        = text_field_tag "search[start_date]", adv_search_value(params,"start_date"), :class => "mdl-textfield__input", :id => "date-start",  :type => "text"
        %label.mdl-textfield__label{:for => "select"} Search by Start Date
    .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
      .moreBtn.collapseminus
        = custom_button_tag_eventsearch "Search", "Hide" 
        / =======================
    .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
      .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
        = text_field_tag "search[end_date]", adv_search_value(params,"end_date"), :class => "mdl-textfield__input", :id => "date-end",  :type => "text"
        %label.mdl-textfield__label{:for => "select"} Search by End Date
        / ====================
    / .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
    /   .mdl-textfield.mdl-js-textfield
    /     = select_tag "search[order_by]",options_for_select([["Upcoming","upcoming"],["Ongoing", "ongoing"], ["Past", "past"]], :selected => adv_search_value(params,"order_by")), :prompt => 'Search by Event Category'
    / .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
    /   .mdl-textfield.mdl-js-textfield
    /     = select_tag "search[order_by_status]",options_for_select([["Pending","pending"],["Rejected", "rejected"],["Published", "published"],["Approved", "approved"]], :selected => adv_search_value(params,"order_by_status")), :prompt => 'Search by Status'    
    /     = hidden_field_tag :admin_search, "true"
    /     = hidden_field_tag :adv_search, "true"
    / ,["Active", "active"],["Deactive", "deactive"]

app/views/admin/events/_event_table.html.haml
%table.table.mdl-data-table.fullwidth.ml-table-striped.ml-table-bordered{"template-pagination" => "custom/pager"}
  - @events.each do |f|         
    %tr
      %td.text-left{"data-title" => "'Event Name'", :filter => "{ 'firstname': 'text' }", :sortable => "'firstname'"}
        =f.event_name
      %td{"data-title" => "'Event Code'", :sortable => "'lastname'"} 
      %td.IconDrp{"data-title" => "''"}
        %button.mdl-button.mdl-js-button.mdl-button--icon{:id => "demo-menu-lower-right#{f.id}"}
          %i.material-icons more_vert
      %ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{:for => "demo-menu-lower-right#{f.id}"}
        = link_to edit_admin_client_event_path(f.client_id, f.id),:class => "mdl-menu__item" do
          Edit
        = link_to admin_client_event_path(f.client_id, f.id),:class => "mdl-menu__item" do
          / %i.material-icons.center visibility
          Show  
        = link_to admin_client_event_path(f.client_id, f.id),method: :delete,:class =>"waves-effect waves-light btn" do
          %i.material-icons.center  
            delete
        - if user_signed_in? and (current_user.has_role? :super_admin or current_user.has_role? :licensee_admin)
          = link_to "/admin/assign_client_to_user?resource_type=event&resource_id=#{f.id}&link=#{request.path_info}",:class => "mdl-menu__item" do
            %i.material-icons.center{:title => "give permision"} vpn_key

app/views/admin/events/_form_about.html.haml
.save_button.mdl-card
  = form_for [:admin, @client, @event], :builder => CustomFormBuilder do |f|
    .mdl-grid
      = f.custom_text_area_field :about,"About", :value => "#{@event.description.present? ? @event.description : ""}"
      = hidden_field_tag :update_about, true
    = f.custom_submit_button "SAVE"
    .mdl-button.mdl-js-button.mdl-button--raised.mdl-color--light-blue-600.mdl-js-ripple-effect.btnsubmit.m-l-18
      .mdl-cell--12-col.mdl-cell--12-col-tablet
        = back_button(:back)
  
  
  

app/views/admin/events/_images_fields.html.haml
= f.file_field :image

app/views/admin/events/_mobile_application_dashboard.html.haml
.row
  %section.content
    
    %h4.heading-borderCard.m-l-10.m-b-20
      Content
    - @count = 0
    / - if (current_user.has_role? :moderator) and (!current_user.has_role? :db_manager)
    - if (current_user.has_role_for_event?("moderator", @event.id,session[:current_user_role])) and (!current_user.has_role_for_event?("db_manager", @event.id,session[:current_user_role]))
      - if show_card("polls")
        = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "polls_1.png", :objs => @event.polls, :url => "polls", :@count => @count}
      - if show_card("conversations")
        = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "conversations.png", :objs => @event.conversations, :url => "conversations", :@count => @count}
      - if show_card("qnas")
        = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "Q&A.png", :objs => @event.qnas, :url => "qnas", :@count => @count}
    - else
      / - if (current_user.has_role? "db_manager")
      - if (current_user.has_role_for_event?("db_manager", @event.id,session[:current_user_role]))
        - if show_card("speakers") 
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "speakers.png", :objs => @event.speakers, :url => "speakers", :@count => @count}
        - if show_card("agendas")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "agenda.png", :objs => @event.agendas, :url => "agendas", :@count => @count}
        - if show_card("invitees")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "invitees.png", :objs => @event.invitees, :url => "invitees", :@count => @count}
        - if show_card("my_travels")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "travel.png", :objs => @event.my_travels, :url => "my_travels", :@count => 0}
        - if show_card("qr_code")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "qr_code.png", :objs => @event, :url => "qr_code", :@count => 0}
        / -elsif !(current_user.has_role? "db_manager")  
      -elsif (!current_user.has_role_for_event?("db_manager", @event.id,session[:current_user_role]))
        - if show_card("abouts")  
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "about.png", :objs => @event, :url => "abouts"}
        - if show_card("speakers") 
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "speakers.png", :objs => @event.speakers, :url => "speakers", :@count => @count}
        - if show_card("agendas")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "agenda.png", :objs => @event.agendas, :url => "agendas", :@count => @count}
        - if show_card("invitees")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "invitees.png", :objs => @event.invitees, :url => "invitees", :@count => @count}
        - if show_card("awards")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "awards_2.png", :objs => @event.awards, :url => "awards", :@count => @count}
        - if show_card("faqs")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "faq.png", :objs => @event.faqs, :url => "faqs", :@count => @count}
        - if show_card("galleries")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "galler_1y.png", :objs => @event.images, :url => "images", :@count => @count}
        - if show_card("contacts")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "contact_us.png", :objs => @event.contacts, :url => "contacts", :@count => @count}
        - if show_card("highlight_images")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "galler_1y.png", :objs => @event.highlight_images, :url => "highlight_images", :@count => @count}
        - if show_card("event_highlights")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "event_highlights.png", :objs => @event, :url => "event_highlights", :@count => @count}
        - if @event.marketing_app.blank?
          - if show_card("venue")
            = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "venue.png", :objs => @event, :url => "venue", :@count => 0} 
        - if show_card("sponsors")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "sponsor.png", :objs => @event.sponsors, :url => "sponsors", :@count => @count}
        - if show_card("notes")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "note.png", :objs => @event, :url => "notes", :@count => 0}
        - if show_card("qr_code")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "qr_code.png", :objs => @event, :url => "qr_code", :@count => 0}  
        - if show_card("exhibitors")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "Exhibitor-breadcumb.png", :objs => @event.exhibitors, :url => "exhibitors", :@count => @count}
        - if show_card("my_profile")  
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "my_profile.png", :objs => @event, :url => "my_profile", :@count => 0}
        - if show_card("favourites")  
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "myfavourite.png", :objs => @event, :url => "favourites", :@count => 0}  
        - if false#show_card("my_calendar")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "My_calender.png", :objs => @event, :url => "my_calendar", :@count => 0}
        - if false#show_card("qr_code")  
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "my-profile.png", :objs => @event.invitees, :url => "qr_code"}
        - if show_card("custom_page1s")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "custom.png", :objs => @event.custom_page1s, :url => "custom_page1s", :@count => 0}
        - if show_card("custom_page2s")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "custom.png", :objs => @event.custom_page2s, :url => "custom_page2s", :@count => 0}
        - if show_card("custom_page3s")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "custom.png", :objs => @event.custom_page3s, :url => "custom_page3s", :@count => 0}
        - if show_card("custom_page4s")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "custom.png", :objs => @event.custom_page4s, :url => "custom_page4s", :@count => 0}

        - if show_card("custom_page5s")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "custom.png", :objs => @event.custom_page5s, :url => "custom_page5s", :@count => 0} 

        - if show_card("my_travels")
          = render :partial => "admin/events/cards", :locals => {:icon => '', :img => "travel.png", :objs => @event.my_travels, :url => "my_travels", :@count => 0}   

app/views/admin/events/_new_event_card.html.haml
.col-sm-3.col-xl-3
  .panel.panel-tile
    .panel-body
      .row.pv5
        .col-xs-5.ph10
          = image_tag(image_path)
        .col-xs-7.pl5
          %h6.text-muted
            - if feature_count.blank?
              = link_to card_title, manage_link
            - else
              = card_title
          %h2.fs30.mt5.mbn
            - if feature_count.present? 
              = link_to feature_count, manage_link
      .row.pv5.AddmoreCard
        .col-xs-12.ph5
          - if !(current_user.has_role? :db_manager)
            = link_to new_label, new_link, :class => 'displayBlock'
            - if card_title == 'Mobile App' and @multi_mobile_applications.present? and @event.mobile_application.blank?
              = link_to 'Add To Existing Multi-Event app', admin_client_mobile_applications_path(:client_id => @event.client_id, :feature => 'events', :event_id => @event.id)
            / - elsif card_title == 'Registration' and @event.registration_settings.present?
            /   = link_to 'Manage Registration Setting', edit_admin_event_registration_setting_path(:event_id => @event.id, :id => @event.registration_settings.last.id)

app/views/admin/events/_upcomming_and_last_event_search.html.haml
.rightBtn.ManageeventBtn
  = link_to "UPCOMING EVENT", '#', {:class => "waves-effect waves-light btn event1", :for => "upcoming" }
  = link_to "ONGOING EVENT", '#', {:class => "waves-effect waves-light btn event1", :for => "today" }
  = link_to "PAST EVENT", '#', {:class => "waves-effect waves-light btn event1", :for => "past" }
  = link_to "ALL EVENT", '#', {:class => "waves-effect waves-light btn event1", :for => "all" }
:javascript
  $('.event1').click(function(){
    $('.event_type').val($(this).attr('for'))
    $('form').submit();
  })

app/views/admin/events/edit.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'Edit Event'}

- if false
  %main.mdl-layout__content.mdl-color--grey-100.page.ng-scope
    %section.menus
      .mdl-color--light-blue-800.eventDetailSection.relative.clear
        .p-20.height150
          / .eventLogoDiv
          /   = image_tag(@event.logo_url(:large))
          -if params[:gallary].present?
            .displayInlineBlock.m-l-20
              %h3.mdl-color-text--white.m-t-20.m-b-5 Edit Gallery
          -else
            .displayInlineBlock.m-l-20
              %h3.mdl-color-text--white.m-t-20.m-b-5="Edit #{(params["data"] == "about" ? "About" : "Event")}"
        .mdl-cell--13-col.mdl-cell--13-col-tablet.mdl-cell--13-col-phone
          .p-40.ml-card-holder.mdl-card
            .mdl-card
              .p-b-40.p-r-40.p-l-40
                - if params["data"] == "about"
                  = render :partial => 'form_about'
                -else
                  = render :partial => 'form'

app/views/admin/events/new.html.haml
- if (params[:feature].present? and params[:redirect_page].present? and params[:redirect_page] == "copy_event")
  = render :partial => 'layouts/layout_form', :locals => {:page => 'Copy Event'}
-else
  = render :partial => 'layouts/layout_form', :locals => {:page => 'New Event'}

app/views/admin/events/new_event_to_user.html.haml
%main.mdl-layout__content.mdl-color--grey-100.page.ng-scope
  %section.menus
    .mdl-color--light-blue-800.eventDetailSection.relative.clear
      .p-20.height150
        / .eventLogoDiv
        /   %img{:src => "/assets/logo_img.jpg"}/
        .displayInlineBlock.m-l-20
          %h3.mdl-color-text--white.m-t-20.m-b-5 Add Users To Event
      .mdl-cell--13-col.mdl-cell--13-col-tablet.mdl-cell--13-col-phone
        .p-40.ml-card-holder.mdl-card
          .mdl-card
            .p-b-40.p-r-40.p-l-40
              = render :partial => 'user_form'
         