config/routes.rb
Rails.application.routes.draw do

mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'
namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings,:time_zones
  resources :profiles, :manage_mobile_apps, :downloads, :external_login
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :eventfeatures_contents
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events do
    end
  end
  resources :mobile_applications do
    resources :external_login
  end
  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :warehouse_timers
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s,:telecallers,:invitee_datas,:my_travels,:venue_sections,:invitee_accesses,:invitee_searches
    
    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations

  end
  # resources :imports
end
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
    end
  end
end

app/controllers/admin/licensees_controller.rb
class Admin::LicenseesController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user
  before_filter :authenticate_super_admin
  before_filter :set_current_licensee, :only => [:show]

  def index
    @licensees = User.unscoped.where(:license => true).paginate(page: params[:page], per_page: 10).check_deleted_record.order('created_at DESC')
    @licensees = User.search(params,@licensees, user_type = "Licensee") if params[:search].present?
  end   

  def new
    @licensee = User.new
  end

  def create 
    @licensee = User.new(licensee_params)
    if @licensee.save
      @licensee.change_status_for_super_admin
      redirect_to admin_licensees_path
    else
      render :action => 'new'
    end
  end

  def edit
    @licensee = User.unscoped.find(params[:id])
  end

  def update
    if params[:status]
      @licensee = User.unscoped.find_by_id(params[:id])
      if @licensee.present?
        @licensee.perform_event(params[:status]) 
      end
      redirect_to admin_licensees_path(:page => params[:page])
    elsif params[:deleted].present?
      @licensee = User.unscoped.find(params[:id])
      @licensee.update_column(:deleted,"#{params[:deleted]}")
      redirect_to admin_licensees_path(:page => params[:page])
    elsif params[:user]
      @licensee = User.unscoped.find(params[:id])
        if @licensee.update_attributes(licensee_params)
          redirect_to admin_licensees_path
        else
          render :action => "edit"
        end
    else
      render :action => "edit"
    end
  end


  def show
    @licensee = User.unscoped.find(params[:id])
    @clients = Client.with_roles(@licensee.roles.pluck(:name), @licensee)
    @event_count = @clients.map{|c| c.events.count}.sum
  end

  def destroy
    @licensee = User.unscoped.find(params[:id])
    if @licensee.destroy
      redirect_to admin_licensees_path
    end
  end

  protected

  def licensee_params
    params.require(:user).permit!
  end

  def set_current_licensee
    session['licensee_user_id'] = current_user.id
  end

end

app/views/admin/licensees/_advance_search.html.haml
= form_tag admin_licensees_url, :method => :get do
  .mdl-grid
    = custom_text_field_tag "search[first_name]", "Search by Name" ,adv_search_value(params,"first_name")
    = custom_text_field_tag "search[email]", "Search by Email id" ,adv_search_value(params,"email")
    .mdl-cell--4-col.mdl-cell--4-col-tablet.mdl-cell--4-col-phone.m-8
      .moreBtn.collapseminus
        %a.f-right.m-t-5{:href => "javascript:void(0);"}
          Hide
        = submit_tag "SEARCH", :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect mdl-color--light-blue-600 f-right m-r-35"
    .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
      .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
        = select_tag "search[package_type]", options_for_select([["Silver", "silver"], ["Gold", "gold"],["Diamond","diamond"],["Platinum","platinum"]], :selected => adv_search_value(params,"package_type")), :prompt => 'Package Type'#rescue nil
    .mdl-cell--4-col.mdl-cell--4-col-tablet.m-8
      .mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label
        = select_tag "search[status]", options_for_select([["Pending", "pending"], ["Rejected", "reject"],["Deactive","deactive"],["Active","active"]], adv_search_value(params,"status")), :prompt => 'Licensee Status'
        = hidden_field_tag :admin_search, "true"
        = hidden_field_tag :adv_search, "true"
       

app/views/admin/licensees/_card.html.haml
%li.grid.eventDetialDiv.angular-grid-item
  .mdl-card.mdl-shadow--0dp
    .mdl-card__supporting-text
      %a.displayInlineBlock.mdl-color--light-blue-600.mdl-button--fab.m-r-15
        %i.mdl-color-text--white.material-icons view_agenda
      .displayInlineBlock
        - if obj == "client"
          %span.font35.displayBlock.p-v-5
            = @clients.length
          = "Client"
        - if obj == "event"
          %span.font35.displayBlock.p-v-5
            = @event_count
          Event
        - if obj == "licensee"
          %span.font16.displayBlock.p-v-5
            = "Package Type"
          = @licensee.package_type || "Trial"                       

app/views/admin/licensees/_form.html.haml
.save_button.mdl-card.agendaheight  
  = form_for [:admin, @licensee],:url => params[:action] == "new" || params[:action] == "create" ? admin_licensees_path : admin_licensee_path, :builder => CustomFormBuilder do |f|
    .mdl-grid.mdl-shadow--1dp.p-b-25
      .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
        %h4.heading-border.p-t-10
          General Information
          / %a{:href => 'javascript:void(0);', :class =>'helpTag testhelp'}
          /   what's this?
      = render :partial => "admin/layouts/whats_this_popup", :locals => {:image_name => "licensee_generalInfo.jpg", :section_id => "licensee_general_section"}
      = f.custom_text_field :first_name, "first Name *"
      = f.custom_text_field :last_name, "Last Name *"
      = f.custom_text_field :company, "Company Name *"
      - if params[:action] == "edit"
        = f.custom_text_field :email, "Email id *", :value => f.object.email.present? ? f.object.email : '',:readonly => true
      -else 
        = f.custom_text_field :email, "Email id *", :value => f.object.email.present? ? f.object.email : ''
      - if f.object.new_record?
        = f.custom_text_field :password, "Password *"
      = f.new_custom_file_browser_field :licensee_logo, "Licensee logo (250x50) png only ", :id => "uploadBtn", :value => f.object.licensee_logo_file_name, :action=> params[:action],"background"=>"false"
      .field_with_errors{:style => "margin-left:35%;margin-top:-2%;"}
        .span{:class => "errorMessage"}
          = f.object.errors.messages[:licensee_logo_content_type].join("") rescue nil
      = f.hidden_field :license , :value => true
      = f.custom_text_field :no_of_event, "Nbr. of events", :value => f.object.no_of_event.present? ? f.object.no_of_event : ''
      = f.custom_text_field :licensee_start_date, "Licensee Start Date", :id => "date-start", :value => f.object.licensee_start_date.present? ? f.object.licensee_start_date.strftime('%d/%m/%Y') : ''  
      = f.custom_text_field :licensee_end_date, "Licensee End Date", :id => "date-end",:value => f.object.licensee_end_date.present? ? f.object.licensee_end_date.strftime('%d/%m/%Y') : ''
    .fixed-activon-btn-new  
      = f.custom_submit_button "SAVE"
      .mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.btnsubmit.m-l-18.cancelBg
        .mdl-cell--12-col.mdl-cell--12-col-tablet.cancelbtn
          = back_button(:back)
:javascript
  $(window).load(function(){
    $('.gui-file').change(function(){
      filename = $(this)[0].files[0].name;
      $(".gui-input").val(filename);
    });
  })     



- if false
  .save_button.mdl-card.agendaheight  
  = form_for [:admin, @licensee],:url => params[:action] == "new" || params[:action] == "create" ? admin_licensees_path : admin_licensee_path, :builder => CustomFormBuilder do |f|
    .mdl-grid.mdl-shadow--1dp.p-b-25
      .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
        %h4.heading-border.p-t-10
          General Information
          / %a{:href => 'javascript:void(0);', :class =>'helpTag testhelp'}
          /   what's this?
      = render :partial => "admin/layouts/whats_this_popup", :locals => {:image_name => "licensee_generalInfo.jpg", :section_id => "licensee_general_section"}
      = f.custom_text_field :first_name, "Full Name *"
      = f.custom_text_field :company, "Company Name *"
      - if params[:action] == "edit" 
        = f.custom_text_field :email, "Email id *", :value => f.object.email.present? ? f.object.email : '',:readonly => true
      -else 
        = f.custom_text_field :email, "Email id *", :value => f.object.email.present? ? f.object.email : ''
      - if f.object.new_record?
        = f.custom_text_field :password, "Password *"
      = f.new_custom_file_browser_field :licensee_logo, "Licensee logo (250x50) png only ", :id => "uploadBtn", :value => f.object.licensee_logo_file_name, :action=> params[:action]
      = f.hidden_field :license , :value => true
      = f.custom_text_field :no_of_event, "Nbr. Of Events Limit", :value => f.object.no_of_event.present? ? f.object.no_of_event : ''
      .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
        .bs-component
          .form-group
            %label.col-lg-4.control-label{:for => "Licensee Start Date"} Start date 
            = f.custom_text_field_date :licensee_start_date, "Licensee Start Date", :id => "date-start", :value => f.object.licensee_start_date.present? ? f.object.licensee_start_date.strftime('%d/%m/%Y') : ''
            / .col-lg-3.timeDropdown
            /   .timeTab
            /     = f.custom_text_field_date :start_time_hour, " ", :class => "hours inputs is-focused", :placeholder => 'HH ', :value => "#{f.object.licensee_start_date.strftime('%l').strip.rjust(2, '0') rescue nil}", :col => '2',:maxlength => "2"
                
            /     = f.custom_text_field_date :start_time_minute, " ", :class => "minutes inputs is-focused", :placeholder => 'MM ', :value => "#{f.object.licensee_start_date.strftime('%M').strip.rjust(2, '0') rescue nil}", :col => '2',:maxlength => "2"
            /     = f.custom_text_field_date :start_time_am, " ", :class => "ampm inputs is-focused", :placeholder => 'AM/PM', :value => "#{f.object.licensee_start_date.strftime('%p') rescue nil}", :col => '3',:maxlength => "2"
      .mdl-cell--12-col.mdl-cell--12-col-tablet.ml-color--shades-white.m-8
        .bs-component
          .form-group
            %label.col-lg-4.control-label{:for => "Licensee End Date"} End Date 
            = f.custom_text_field_date :licensee_end_date, "Licensee End Date", :id => "date-end", :value => f.object.licensee_end_date.present? ? f.object.licensee_end_date.strftime('%d/%m/%Y') : ''
            / .col-lg-3.timeDropdown
            /   .timeTab  
            /     = f.custom_text_field_date :end_time_hour, " ", :class => "hours inputs", :placeholder => 'HH ', :value => "#{f.object.licensee_end_date.strftime('%l').strip.rjust(2, '0') rescue nil}", :col => '2',:maxlength => "2"
            /     = f.custom_text_field_date :end_time_minute, " ", :class => "minutes inputs", :placeholder => 'MM ', :value => "#{f.object.licensee_end_date.strftime('%M').strip.rjust(2, '0') rescue nil}", :col => '2',:maxlength => "2"
            /     = f.custom_text_field_date :end_time_am, " ", :class => "ampm inputs", :placeholder => 'AM/PM', :value => "#{f.object.licensee_end_date.strftime('%p') rescue nil}", :col => '3',:maxlength => "2"          
    .fixed-activon-btn-new  
      = f.custom_submit_button "SAVE"
      .mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.btnsubmit.m-l-18.cancelBg
        .mdl-cell--12-col.mdl-cell--12-col-tablet.cancelbtn
          = back_button(:back)
 

app/views/admin/licensees/_index.html.haml
- if !objs.present? and !params[:admin_search].present?
  .mdl-typography--text-center.BlnkTxt.p-t-10
    = render :partial => 'admin/layouts/index_no_data_message', :locals => {:title => "licensees", :url => "/admin/licensees/new", :msg => 'test'}
-elsif !objs.present? and params[:admin_search].present?
  .mdl-typography--text-center.BlnkTxt.p-t-10
    = get_search_data("licensees")
- else  
  %table.table.mdl-data-table.fullwidth.ml-table-striped.ml-table-bordered.font16{"template-pagination" => "custom/pager"}
    %tr
      %th Name
      %th Company Name
      %th Email id
      %th Status
      %th Nbr. of events
      %th Start Date
      %th End Date
      %th
      - if objs.present?
        - objs.each do |licensee| 
          %tr
            %td.font16= link_to "#{licensee.get_full_name}", edit_admin_licensee_path(:id => licensee.id)
            %td.font16= licensee.company.capitalize rescue nil
            %td.font16= link_to "#{licensee.email}", admin_licensee_path(licensee.id)
            %td.font16= licensee.status.capitalize rescue nil
            / %td.font16= licensee.get_licensee_events_count
            - if licensee.no_of_event.present?
              %td.font16= "#{licensee.get_licensee_events_count} of #{licensee.no_of_event}"
            - else
              %td.font16= licensee.get_licensee_events_count
            %td.font16= licensee.licensee_start_date.strftime('%d-%m-%Y') rescue nil
            %td.font16= licensee.licensee_end_date.strftime('%d-%m-%Y') rescue nil
            %td.IconDrp
              = more_vert_button(licensee.id)
              %ul.mdl-menu.mdl-menu--bottom-right.mdl-js-menu.mdl-js-ripple-effect{:for => "demo-menu-lower-right#{licensee.id}"}
                = link_to edit_admin_licensee_path(licensee.id),:class => "mdl-menu__item" do
                  Edit
                - licensee.aasm.events.each do |eve|
                  = link_to "#{eve.name.to_s.titlecase}".html_safe,{:action=>"update", :controller=>"admin/licensees", :id => licensee.id, :status => eve.name.to_s, :page => params[:page]}, :method => "put", :data => { confirm: 'Are you sure, you want to change the status.'},:class => "mdl-menu__item"
                = link_to "Delete",{:action=>"update", :controller=>"admin/licensees", :id => licensee.id, :deleted => "true", :page => params[:page]}, :method => "put", :data => { confirm: 'Are you sure, you want Delete the Licensee.'},:class => "mdl-menu__item"
  = will_paginate objs

app/views/admin/licensees/_search.html.haml
.mdl-cell.mdl-cell--6-col.mdl-cell--12-col-tablet.mdl-cell--12-col-phone.newsearchlaypout.HideTabularData
  = form_tag admin_licensees_url, :method => :get do
    .mdl-js-textfield.mdl-textfield--floating-label.mdl-grid.f-right.m-r-25.m-t-10 
      #select-container.mdl-textfield.mdl-js-textfield.mdl-textfield--floating-label.mdl-cell--6-col.mdl-cell--5-col-tablet.mdl-cell--12-col-phone  
      /   = custom_basic_text_field_tag "search""[keyword]", "", basic_search_value(params)
      /   = hidden_field_tag :admin_search, "true"
      /   / = hidden_field_tag :page, params[:page] 
      / = custom_basic_button_tag "SEARCH"
      = custom_advance_search_link_tag "Search"

app/views/admin/licensees/edit.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'Edit Licensee'}

app/views/admin/licensees/index.html.haml
= render :partial => 'admin/layouts/index_header', :locals => {:objs => @licensees}
/ -if @licensees.present?
/   = render :partial => 'admin/layouts/more_links'

app/views/admin/licensees/new.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'New Licensee'}

app/views/admin/licensees/show.html.haml
%main.mdl-layout__content.mdl-color--grey-100.page.ng-scope
  %section.menus
    .mdl-color--light-blue-800.relative.clear
      - page =  @licensee.first_name.capitalize rescue nil
      = render :partial => "/admin/dashboards/breadcumb_links",:locals => {:name => params[:controller],:page => page}
      / .p-20
      /   .displayInlineBlock
      /     %h3.mdl-color-text--white.m-t-20.m-b-5
      /       = @licensee.first_name.capitalize rescue nil
          
      /   %p.m-t-20.headingInfo
      /     = link_to edit_admin_licensee_path(:id => params[:id]) do 
      /       %i.material-icons.mdl-color-text--white edit
    .mdl-cell--13-col.mdl-cell--13-col-tablet.mdl-cell--13-col-phone
      .ml-card-holder
        .ml-color--shades-white.mdl-shadow--1dp
          %form{:action => "#"}
            .mdl-grid
              = show_field("Name: ", @licensee.first_name).html_safe
              = show_field("Email id: ", @licensee.email).html_safe
              .mdl-cell--2-col.mdl-cell--4-col-tablet.ml-color--shades-white.m-8
                %a.viewMoreLink.floatRight{:href => "javascript:void(0);"}
                  %span.verticalTop view more
            .mdl-grid.toggleDiv
              = show_field("Company Name: ",@licensee.company).html_safe
              = show_field("Package Type: ",@licensee.package_type).html_safe
    .mdl-cell.mdl-cell--12-col.mdl-cell--12-col-tablet.mdl-cell--12-col-phone.p-20
      .ml-card-holder
        #gridWrap
          %ul.dynamic-grid.angular-grid.galleryLayout{"angular-grid" => "images", "grid-width" => "250", "gutter-size" => "20", "refresh-on-img-load" => "true"}
            - if @clients.present?
              = render :partial => "admin/licensees/card", :locals => {:obj => "client"}
            - if @event_count > 0
              = render :partial => "admin/licensees/card", :locals => {:obj => "event"}
            - if @licensee.present?
              = render :partial => "admin/licensees/card", :locals => {:obj => "licensee"}