config/routes.rb
Rails.application.routes.draw do

mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'
namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings,:time_zones
  resources :profiles, :manage_mobile_apps, :downloads, :external_login
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :eventfeatures_contents
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events do
    end
  end
  resources :mobile_applications do
    resources :external_login
  end
  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :warehouse_timers
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s,:telecallers,:invitee_datas,:my_travels,:venue_sections,:invitee_accesses,:invitee_searches
    
    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations

  end
  # resources :imports
end
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
	
  belongs_to :imageable, polymorphic: true
  has_many :favorites, as: :favoritable, :dependent => :destroy
	has_attached_file :image, {:styles => {:large => "640x640>",
                                         :small => "200x200>", 
                                         :thumb => "60x60>"},
                             :convert_options => {:large => "-strip -quality 90", 
                                         :small => "-strip -quality 80", 
                                         :thumb => "-strip -quality 80"}
                                         }.merge(PICTURE_IMAGE_PATH)

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"],:message => "please select valid format."
  
  before_create :set_sequence_no
  
  default_scope { order('sequence') }
  
  def image_url(style=:large)
  	style.present? ? self.image.url(style) : self.image.url
	end

  def set_sequence_no
    self.sequence = (Event.find(self.imageable_id).images.pluck(:sequence).compact.max.to_i + 1)rescue nil
  end

  def to_jq_upload
    {
      "name" => read_attribute(:image),
      "size" => image.size,
      "url" => image.url(:thumb),
      "thumbnail_url" => image.url(:thumb),
      "delete_url" => image.url(:thumb),
      "delete_type" => "DELETE" ,
      "id" => self.id
    }
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user, :authorize_event_role, :find_features
  
	def index
    @image = @event.images
	end

	def new
    @image = @event.images.build
    render "add_new"
	end

  def create
    #@image = @event.images.build
    #@image = @event.images.build(image_params)
    @image = @event.images.build(:image => params[:image][:image].first)
    if @image.save
      respond_to do |format|
        format.html {  
          render :json => { :files => [@image.to_jq_upload], 
          :content_type => 'text/html',
          :layout => false
         }
        }
        format.json {  
          render :json => {:files => [@image.to_jq_upload] }
        }
      end
    else 
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  def update
    #@image.update_attributes(image_params)
    redirect_to admin_event_images_path(:event_id => @event.id) 
  end

  def destroy
    @image.destroy
    redirect_to admin_event_images_path(:event_id => @event.id) 
  end

	protected

  def image_params
    params.require(:image).permit!
  end

end

app/controllers/api/v1/images_controller.rb
class Api::V1::ImagesController < ApplicationController
  skip_before_action :load_filter
  skip_before_action :authenticate_user!
  respond_to :json
  
  def index
    mobile_application = MobileApplication.find_by_submitted_code(params[:mobile_application_code]) || MobileApplication.find_by_preview_code(params[:mobile_application_code]) || MobileApplication.find_by_id(params["mobile_application_id"]) || MobileApplication.find_by_preview_code(params[:mobile_application_preview_code])

    # if params[:mobile_application_preview_code].present?
    #   mobile_application = MobileApplication.find_by_preview_code(params[:mobile_application_preview_code])
    # elsif params[:mobile_application_code].present? or params["mobile_application_id"].present?
    #   mobile_application = MobileApplication.where('submitted_code =? or preview_code =? or id =?', params[:mobile_application_code], params[:mobile_application_code], params["mobile_application_id"]).first
    # end
    
    event_status = ((params[:mobile_application_code].present? and mobile_application.present? and mobile_application.submitted_code == params[:mobile_application_code].upcase) ? ["published"] : ["approved","published"])
    if mobile_application.present?
      events = mobile_application.events 
      event = events.where(:id => params[:event_id], :status => event_status) rescue nil
      if event.present?
        galleries = Image.where(:imageable_id => event.first.id,:imageable_type => "Event") rescue []
        render :staus => 200, :json => {:status => "Success",:galleries => galleries.as_json(:except => [:image_file_name,:image_content_type,:image_file_size,:image_updated_at], :methods => [:image_url]) } rescue []
      else
        render :status => 200, :json => {:status => "Failure", :message => "Event Not Found."}
      end 
    else
      render :status => 200, :json => {:status => "Failure", :message => "Mobile Application Not Found."}
    end 
  end
end

app/views/admin/images/_add_form.html.haml
.save_button.mdl-card.mdl-shadow--1dp
  = form_for [:admin, @event, @image], :html => { :multipart => true, :id => "fileupload"  } do |f|
    .row.fileupload-buttonbar
      .col-lg-7
        %span.btn.btn-success.fileinput-button
          %i.icon-plus.icon-white
          %span Add files...
          = f.file_field :image, multiple: true
        %button.btn.btn-primary.start{:type => "submit"}
          %i.icon-upload.icon-white
          %span Start upload 
        %button.btn.btn-warning.cancel{:type => "reset"}
          %i.icon-ban-circle.icon-white
          %span Cancel upload
      .col-lg-5.fileupload-progress.fade
        .progress.progress-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", :role => "progressbar"}
          .progress-bar.progress-bar-success{:style => "width:0%;"}
        .progress-extended       
    %table.table.table-striped{:role => "presentation"}
      %tbody.files
.fixed-activon-btn-new
  .mdl-button.mdl-js-button.mdl-button--raised.mdl-js-ripple-effect.btnsubmit.m-l-18.cancelBg
    .mdl-cell--12-col.mdl-cell--12-col-tablet.cancelbtn
      - if params[:type] == "dashboard_new"
        - url = admin_event_mobile_application_path(:event_id => @event.id, :id => @event.mobile_application.id,:type => "show_content")
      -else
        - url = admin_event_images_path(:event_id => @event.id)
      = link_to  url do
        %span.waves-effect.waves-light.btn
          CANCEL


= stylesheet_link_tag 'css/bootstrap.min','css/blueimp-gallery.min', 'css/jquery.fileupload', 'css/jquery.fileupload-ui'

= javascript_include_tag 'jquery-1.11.3.min','js/jquery.ui.widget', 'js/tmpl.min' ,'js/load-image.all.min', 'js/canvas-to-blob.min', 'js/bootstrap.min', 'js/jquery.blueimp-gallery.min','js/jquery.fileupload', 'js/jquery.fileupload-process', 'js/jquery.fileupload-image', 'js/jquery.fileupload-ui', 'js/main', 'js/test' 

/ :javascript


  
%script#template-download{:type => "text/x-tmpl"}
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  %tr.template-download.fade
    %td
      %span.preview
        {% if (file.url) { %}
        %a{"data-gallery" => "", :download => "{%=file.name%}", :href => "{%=file.url%}", :title => "{%=file.name%}"}
          %img{:src => "{%=file.url%}"}/
        {% } %}
    %td
      %p.name
        {% if (file.url) { %}
        <a href="/admin/events/#{@event.id}/images", method='post'>{%=file.name%}
        {% } else { %}
        %span {%=file.name%}
        {% } %}
      {% if (file.error) { %}
      %div
        %span.label.label-danger Error
        {%=file.error%}
      {% } %}
    %td
      %span.size {%=o.formatFileSize(file.size)%}
    %td
      {% if (file.url) { %}
      <a href="/admin/events/#{@event.id}/images/{%=file.id %}", data-method='delete'>{%=file.name%}
      %i.glyphicon.glyphicon-trash
      %span Delete
      %span
        {% } else { %}
        %button.btn.btn-warning.cancel
          %i.glyphicon.glyphicon-ban-circle
          %span Cancel
        {% } %}
  {% } %}

%script#template-upload{:type => "text/x-tmpl"}
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  %tr.template-upload.fade
    %td
      %span.preview
    %td
      %p.name {%=file.name%}
      %strong.error.text-danger
    %td
      %p.size Processing...
      .progress.progress-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "0", :role => "progressbar"}
        .progress-bar.progress-bar-success{:style => "width:0%;"}
    %td
      {% if (!i && !o.options.autoUpload) { %}
      %button.btn.btn-primary.start{:disabled => ""}
        %i.glyphicon.glyphicon-upload
        %span Start
      {% } %}
      {% if (!i) { %}
      %button.btn.btn-warning.cancel
        %i.glyphicon.glyphicon-ban-circle
        %span Cancel
      {% } %}
  {% } %}

app/views/admin/images/_index.html.haml
- @images.each_with_index do |image,index|
  .mdl-cell--2-col.mdl-cell--4-col-tablet.imggallery
    = link_to admin_event_image_path(:event_id => image.imageable_id, :id => image.id), :method => 'delete',data: { confirm: 'Are you sure?' }, :class => "galleryImg" do
      %span.galleryclose
        X
    = image_tag(image.image_url(:small), :size => "200x200")
    .orderseq
      - if index != 0
        %span.fleft
          = link_to "",admin_event_sequence_path(:event_id => image.imageable_id, :id => image.id, :seq_type => "up", :feature_type => "images"),:class => "gallerydownarrow", :method => "put", :remote => true
      - if image.sequence.to_i != 0 and (@images.length - 1) != index
        %span
          = link_to "",admin_event_sequence_path(:event_id => image.imageable_id, :id => image.id, :type => "down", :feature_type => "images"),:class => "galleryuparrow", :method => "put", :remote => true

app/views/admin/images/add_new.html.haml
= render :partial => 'layouts/layout_form', :locals => {:page => 'Add Gallery'}

app/views/admin/images/index.html.haml
%main.mdl-layout__content.mdl-color--grey-100.page.ng-scope               
  %section.tables-data
    .ml-header.relative.clear.mdl-color--light-blue-800
      .mdl-grid.mdl-grid--no-spacing
        .mdl-cell.mdl-cell--6-col.mdl-cell--12-col-tablet
          %h3.mdl-color-text--white.m-t-15.p-l-40.p-v-20 Manage Gallery
        / = render :partial => 'image_search'
    .mdl-grid.mdl-grid--no-spacing
      .mdl-cell.mdl-cell--12-col.mdl-cell--12-col-tablet.mdl-cell--12-col-phone
        .p-35.ml-card-holder.ml-card-holder-first.HeaderHeight
          .mdl-card.mdl-shadow--1dp.m-b-30.clients
            .mdl-card__title.mdl-color--light-blue-600.mdl-typography--text-right.displayBlock
              %h2.mdl-card__title-text.mdl-color-text--white.displayBlock.mdl-typography--text-right.displayBlock.mdl-typography--text-right 
                - if @images.present?
                  = @images.count
                - else 
                  No
                Images
                = render :partial => 'admin/layouts/add_link' 
            - if !@images.present? and !params[:admin_search].present?
              .mdl-typography--text-center.BlnkTxt.p-t-10
                = render :partial => 'admin/layouts/index_no_data_message', :locals => {:title => "images", :url => "/admin/events/#{params[:event_id]}/images/new", :msg => 'test'}
            -elsif !@images.present? and params[:admin_search].present?
              .mdl-typography--text-center.BlnkTxt.p-t-10
                = get_search_data("images")
            - else
              %table.table.fullwidth.ml-table-striped.ml-table-bordered.gallerySequence{"template-pagination" => "custom/pager"}
                %tr
                  %th 
                %tr.galleryTab.mdl-grid--no-spacing.mdl-cell--12-col  
                  %td.mdl-grid.mdl-cell--12-col.mdl-cell--12-col-tablet
                    .sequence_update
                      = render :partial => 'index'