config/routes.rb
Rails.application.routes.draw do

mount Ckeditor::Engine => '/ckeditor'
devise_for :users
as :user do
  get 'passwords/change_password' => 'devise/passwords#edit'
  put 'passwords' => 'devise/passwords#update'
end
#root "admin/dashboards#index"
root "admin/homes#index"
get 'back' => 'application#back'
namespace :admin do
  get 'bee_editor' => 'bee_editors#index'
  get '/mobile_applications/:mobile_application_id/success' => 'external_login#show'
  get '/events/:event_id/success' => 'user_registrations#show'
  get 'bee_editor/token' => 'bee_editors#token'
  get 'bee_editor/template' => 'bee_editors#template'
  # get '/check_email_existance' => 'users#check_email_existance'
  resources :dashboards, :themes, :manage_users, :users, :roles, :homes, :smtp_settings,:time_zones
  resources :profiles, :manage_mobile_apps, :downloads, :external_login
  resources :licensees do
    resources :clients    
  end
  resources :clients do
    resources :users, :eventfeatures_contents
    resources :mobile_applications do
      resources :push_pem_files
    end
    resources :event_groups
    resources :events do
    end
  end
  resources :mobile_applications do
    resources :external_login
  end
  resources :events do
    resources :abouts, :event_highlights, :emergency_exits, :themes, :sequences,:leaderboards, :chats, :invitee_groups, :qr_code_scanners, :warehouse_timers
    resources :speakers, :attendees, :invitees, :agendas, :conversations, :users, :notifications
    resources :event_features, :menus, :faqs, :images, :highlight_images, :feedbacks, :sponsors, :qnas, :feedbacks
    resources :e_kits, :contacts, :panels, :imports, :user_registrations
    resources :groupings, :exhibitors, :manage_feature_status, :analytics, :registration_settings, :custom_page1s, :custom_page2s, :custom_page3s, :custom_page4s, :custom_page5s,:telecallers,:invitee_datas,:my_travels,:venue_sections,:invitee_accesses,:invitee_searches
    
    resources :polls do
      resources :user_polls
    end

    resources :quizzes do
      resources :user_quizzes
    end

    # resources :invitee_datas do
    #   collection do
    #     post 'update_details'
    #   end
    # end

    resources :user_polls, :user_quizzes, :user_feedbacks, :likes, :comments

    resources :mobile_applications do
      resources :store_infos
    end  
    resources :awards do
      resources :winners 
    end
    resources :invitee_structures do
      resources :invitee_datas
    end
    resources :registrations

  end
  # resources :imports
end
  namespace :api do
    namespace :v1 do
      get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
      post 'tokens/get_key' => 'tokens#get_key'#, defaults: {format: 'json'}
      get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
      post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
      post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
      post 'tokens/twitter_authentication' => 'tokens#twitter_authentication', defaults: {format: 'json'}
      resources :events do 
        post 'delete_mobile_data', on: :collection 
        resources :chats
      end
      resources :tokens, :social_media_authentications, :abouts, :agendas, :speakers, :invitees, :leaderboards, :attendees, :images, :ratings, defaults: {format: 'json'} 
      resources :faqs, :notifications, :conversations, :comments, :qnas, :polls,:invitee_trackings, defaults: {format: 'json'}
      resources :awards, :event_features, :sponsors, :likes, :notes, :user_feedbacks,:e_kits, :mobile_applications, :passwords, :my_travels, defaults: {format: 'json'}
    end
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user
  
  def index
    # if current_user.has_role? :db_manager
    #   @count = Event.with_role(:db_manager, current_user)
    # end
    # if current_user.has_role? :moderator
    #   @count = Event.with_role(:moderator, current_user)
    # end
    # if current_user.has_role? :event_admin
    #   @count = Event.with_roles(current_user.roles.pluck(:name), current_user)
    # end
    @count = Event.with_role(session[:current_user_role], current_user)
    client_ids = Client.with_role(session[:current_user_role], current_user).pluck(:id)
    if client_ids.present?
      @count += Event.where(:client_id => client_ids,:marketing_app => nil)
      @count = @count.flatten.uniq
    end
  end
  
  # def index
  #   # if current_user.has_role? :db_manager
  #   #   @count = Event.with_role(:db_manager, current_user)
  #   # end
  #   # if current_user.has_role? :moderator
  #   #   @count = Event.with_role(:moderator, current_user)
  #   # end
  #   # if current_user.has_role? :event_admin
  #   # all_event_ids = @clients.collect{|e| e.events.pluck(:id)}.flatten
  #   # event_ids = current_user.event_ids_with_access(all_event_ids)
  #   # @count = Event.where(:id => event_ids)
  #   # @count = Event.with_roles(current_user.roles.pluck(:name), current_user)

  #   # binding.pry
  #   # end
  # end
end

app/views/admin/dashboards/_breadcumb_links.html.haml
- name = name.split("/").second
- breadcrum_image = MobileApplication::BREADCRUM_IMAGES
%header#topbar.alt
  .topbar-left
    - if params[:controller] == "admin/mobile_applications" and params[:action] == "show" and !current_user.has_role? :moderator
      %ul.publishTab
        - calc_percentage = @event.present? ? "#{@event.avg_review.to_i}" : ''
        %li.progress.mdl-color--grey-500
          = link_to new_admin_event_mobile_application_store_info_path(:event_id => @event.id, :mobile_application_id => @mobile_application.id), :class => 'appsize progress-bar progress-bar-info', "aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{calc_percentage}",:role => "progressbar", :style => "width:  #{calc_percentage}%" do
            %span.reviewBtn
              = "Review (#{calc_percentage}% complete)"
        - if @event.status == 'approved'
          %li.mdl-color--light-blue-600.borderradius
            = link_to new_admin_event_mobile_application_store_info_path(:event_id => @event.id, :mobile_application_id => @mobile_application.id, :event => 'publish'), :data => { confirm: get_publish_event_message}, :class => 'appsize progress-bar progress-bar-info' do
              %span.publishBtn
                = "Publish"
        - elsif @event.status == 'published'
          %li.mdl-color--light-blue-600.borderradius
            = link_to new_admin_event_mobile_application_store_info_path(:event_id => @event.id, :mobile_application_id => @mobile_application.id, :event => 'unpublish'), :data => { confirm: 'Are you sure, you want to Unpublish this.'}, :class => 'appsize progress-bar progress-bar-info' do
              %span.publishBtn
                = "Unpublish"
        - elsif false
          %li.mdl-color--light-blue-600.borderradius      
            = link_to 'javascript:void(0)', :class => 'appsize progress-bar progress-bar-info' do
              %span.publishBtn
                = "Publish"
                
    %ol.breadcrumb  
      %li.breadcrumb-icon
        = image_tag("coloured_icons/#{breadcrum_image[name]}")
      %li.breadcrumb-active.editshowlink
        - if params[:controller] != "admin/dashboards"
          - if page == 'New E-kit'
            = 'New e-KIT'
          -elsif page == "abouts"
            About
          - elsif params["step"] == "event_theme"   
            Look & Feel
          - elsif page == "Edit Profile"
            Edit Profile
          - elsif params[:controller] == "admin/mobile_applications"
            = "#{page}"
          - elsif page == "polls"
            Poll
          - elsif page == "Import conversation"
            Import conversations
          - elsif page == "Features"
            = params[:feature] == "my_calender" ? "Calender" : page
          - else
            = "#{page.humanize.titleize}" if params[:controller] != "admin/events" and "#{page}" != "e-KIT" and params[:controller] != "admin/faqs"
            = "e-KIT" if "#{page}" == "e-KIT"
            = "#{page}" if params[:controller] == "admin/faqs"
            = "#{page}" if params[:controller] == "admin/events"
          - if params[:action] == "show" and params[:controller] != "admin/mobile_applications" and params[:controller] != "admin/manage_mobile_apps" and params[:controller] != "admin/telecallers"
            = show_edit_link(params)  
            = link_to "Copy Data from another Event",admin_client_events_path(:client_id => @event.client_id, :feature => "events",:redirect_page => "copy_event") if @event.mobile_application.blank?

            / admin_client_events_path(:client_id => client_id, :feature => "users", :role => params[:role]) if params[:feature] == "users" and (params[:role] == 'event_admin' or params[:role] == 'moderator') and params[:redirect_page] != "index"

          - if (params[:controller] == "admin/mobile_applications" and ["show","edit"].include?(params[:action])) or (params[:controller] == "admin/themes" and params[:step] == "event_theme") or (params[:controller] == "admin/event_features" and params[:action] == "new") or (params[:controller] == "admin/menus" and params[:action] == "index") 
            .previewTxt    
              -  if @mobile_application.present?
                = "Preview ID: #{@mobile_application.preview_code}" 
              - else
                = "Preview ID: #{@event.mobile_application.preview_code}" 
              = link_to "?" ,"/whats_this/event_feature/breadcumb/AppPreview.jpg", rel: "event_preview_image", title: "Preview Code", :class =>'fancybox PreviewwhtsImg'  
        -else
          Dashboard
          -if false
            %a{:href => "javascript:void();"} Dashboard
      -if false
        %li.breadcrumb-link
          %a{:href => "admin_dashboards_path"} Home
        %li.breadcrumb-current-item
          = "#{name.humanize.titleize}"
      
  
        